version: '3'
services:  
  frontend:    
    build:      
      context: .      
      dockerfile: frontend/Dockerfile.frontend    
    ports:      
      - "3000:3000"    
    volumes:      
      - ./frontend:/app    
    networks:      
    - app-network  
    
  backend:    
    build:      
      context: .      
      dockerfile: backend/Dockerfile.backend    
    environment:
      - PYTHONPATH=/app
    ports:      
      - "5000:5000"    
    volumes:      
      - ./backend:/app    
    networks:      
      - app-network

networks:  
  app-network:    
    driver: bridge