version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d quizdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: production
      DB_HOST: db
      DB_NAME: quizdb
      DB_USER: my_user
      DB_PASS: password
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost:5000/api
        NEXT_PUBLIC_ENV: production
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  db-data: