apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: reinduran/frontend:17
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://k8s-threetie-mainlb-7703746d77-255087660.ap-southeast-2.elb.amazonaws.com/api"
            - name: NEXT_PUBLIC_ENV
              value: "production"
            - name: NEXT_PUBLIC_GITHUB_OAUTH_URL
              value: "https://github.com/login/oauth/authorize?client_id=Ov23lipCg0uto5vUsYoG&redirect_uri=http://k8s-threetie-mainlb-7703746d77-255087660.ap-southeast-2.elb.amazonaws.com/api/auth/github/callback"