apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: rsduran/frontend:4  # Using DockerHub public repo
        imagePullPolicy: Always
        env:
          - name: NEXT_PUBLIC_BACKEND_URL
            value: "http://k8s-threetie-mainlb-b5b9250791-590477292.ap-southeast-2.elb.amazonaws.com/api"  # Replace with your backend service URL
        ports:
        - containerPort: 3000