apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
  namespace: three-tier
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  type: ClusterIP
  selector:
    app: frontend