apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: three-tier
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13  # Using the official PostgreSQL image
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: POSTGRES_DB
            value: quizdb  # Database name for your quiz app
        volumeMounts:
          - name: postgres-volume-1
            mountPath: /var/lib/postgresql/data
          - name: postgres-init
            mountPath: /docker-entrypoint-initdb.d/init.sql
            subPath: init.sql  # Ensure init.sql is executed during initialization
      volumes:
      - name: postgres-volume-1
        persistentVolumeClaim:
          claimName: postgres-volume-claim-1
      - name: postgres-init
        configMap:
          name: postgres-init-sql  # Reference to the ConfigMap holding init.sql