apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim-1
  namespace: three-tier
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi