apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
  labels:
    role: backend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
      - name: backend
        image: rsduran/backend:19  # Update this based on your versioning
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            value: postgresql://user:password@postgres-svc:5432/quizdb  # PostgreSQL connection string
        ports:
        - containerPort: 5000  # Assuming your backend runs on port 5000

        # Add liveness and readiness probes
        livenessProbe:
          httpGet:
            path: /api/health  # Assuming this is your health check endpoint
            port: 5000
          initialDelaySeconds: 10  # Delay before the probe starts
          periodSeconds: 10  # Probe interval

        readinessProbe:
          httpGet:
            path: /api/health  # Assuming this is your health check endpoint
            port: 5000
          initialDelaySeconds: 15  # Delay before starting the readiness check
          periodSeconds: 10  # Probe interval