apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
  labels:
    role: backend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
      - name: backend
        image: rsduran/backend:8  # Update this based on your versioning
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            value: postgresql://my_user:password@postgres:5432/quizdb  # PostgreSQL connection string
        ports:
        - containerPort: 5000  # Assuming your backend runs on port 5000