apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
  labels:
    role: backend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
      - name: backend
        image: rsduran/backend:1  # Update this based on your versioning
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            value: postgresql://user:password@db:5432/quizdb  # PostgreSQL connection string
        ports:
        - containerPort: 5000  # Assuming your backend runs on port 5000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /started
            port: 5000
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30