name: Backend CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clean workspace
        run: git clean -fdx

      - name: Build Docker image
        run: |
          cd backend
          docker system prune -f
          docker container prune -f
          docker build -t reinduran/backend:${{ github.run_number }} -f Dockerfile.backend .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to DockerHub
        run: docker push reinduran/backend:${{ github.run_number }}

      - name: Update Kubernetes deployment
        run: |
          cd Kubernetes-Manifests/Backend
          git config user.email "reineirsamonteduran@gmail.com"
          git config user.name "rsduran"
          imageTag=$(grep -oP '(?<=backend:)[^ ]+' deployment.yaml)
          sed -i "s|reinduran/backend:${imageTag}|reinduran/backend:${{ github.run_number }}|" deployment.yaml
          git add deployment.yaml
          git commit -m "Update backend image to version ${{ github.run_number }}" || echo "No changes to commit"

      - name: Fetch and merge changes
        run: |
          git fetch origin main
          git config pull.rebase false
          git merge -X ours --no-edit origin/main || echo "Merge failed, continuing with local changes"

      - name: Push changes
        if: success()
        run: |
          git push https://rsduran:${{ secrets.GITHUB_TOKEN }}@github.com/rsduran/quiz-app-image-links.git || echo "No changes to push"