name: Frontend CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Docker image
        run: |
          cd frontend
          docker build -t reinduran/frontend:${{ github.run_number }} -f Dockerfile.frontend .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to DockerHub
        run: docker push reinduran/frontend:${{ github.run_number }}

      - name: Update Kubernetes deployment
        run: |
          cd Kubernetes-Manifests/Frontend
          sed -i "s|reinduran/frontend:.*|reinduran/frontend:${{ github.run_number }}|" deployment.yaml
          git config user.email "reineirsamonteduran@gmail.com"
          git config user.name "rsduran"
          git add deployment.yaml
          git commit -m "Update frontend image to version ${{ github.run_number }}" || echo "No changes to commit"
          git push https://rsduran:${{ secrets.GITHUB_TOKEN }}@github.com/rsduran/quiz-app-image-links.git || echo "No changes to push"