name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean workspace
        run: git clean -fdx

      - name: Build Docker image
        env:
          NEXT_PUBLIC_BACKEND_URL: "http://k8s-threetie-mainlb-7703746d77-255087660.ap-southeast-2.elb.amazonaws.com/api"
        run: |
          cd frontend
          docker build --build-arg NEXT_PUBLIC_BACKEND_URL=${{ env.NEXT_PUBLIC_BACKEND_URL }} --progress=plain --no-cache -t reinduran/frontend:${{ github.run_number }} -f Dockerfile.frontend .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to Docker Hub with retries
        run: |
          for i in {1..5}; do
            docker push reinduran/frontend:${{ github.run_number }} && break || sleep 15;
          done

      - name: Update Kubernetes deployment
        run: |
          cd Kubernetes-Manifests/Frontend
          git config user.email "reineirsamonteduran@gmail.com"
          git config user.name "rsduran"
          imageTag=$(grep -oP '(?<=frontend:)[^ ]+' deployment.yaml)
          sed -i "s|reinduran/frontend:${imageTag}|reinduran/frontend:${{ github.run_number }}|" deployment.yaml
          git add deployment.yaml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update frontend image to version ${{ github.run_number }}"

      - name: Pull latest changes from remote
        run: |
          git remote set-url origin https://rsduran:${{ secrets.GITHUB_TOKEN }}@github.com/rsduran/Athena-quiz-app-v2.git
          git pull origin main --rebase

      - name: Push changes if there are any
        if: success()
        run: |
          git push origin main || echo "No changes to push"